---
driver:
  name: vagrant

#driver_config:
#  require_chef_omnibus: latest

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.4

suites:
  - name: server
    run_list:
      - recipe[fwknop::server]
